name: DCG

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  issues: write
  pages: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-coverage:
    runs-on: ubuntu-latest
    outputs:
      latest-commit-message: ${{ steps.run-bazel.outputs.LATEST_MASTER_COMMIT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the version of Java you need
          distribution: 'zulu'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Fetch master branch
        run: git fetch origin master

      - name: Run Bazel Coverage
        id: run-bazel
        run: |
          cd java/spring-boot
          bazel coverage --instrumentation_filter="^//src[/:]" //src/test/func:sample_code_test --combined_report=lcov
          LATEST_MASTER_COMMIT=$(git rev-parse origin/master)
          echo "LATEST_MASTER_COMMIT=$LATEST_MASTER_COMMIT" >> $GITHUB_ENV
          echo "LATEST_MASTER_COMMIT=$LATEST_MASTER_COMMIT" >> $GITHUB_OUTPUT
          python script-coverage.py --commit_id "$LATEST_MASTER_COMMIT"
          git checkout -b origin/gh-pages
          pwd
          genhtml --branch-coverage --output "genhtml$LATEST_MASTER_COMMIT" bazel-out/_coverage/filtered_coverage_report.dat 
          git config --global user.name 'NikhilBRai'
          git config --global user.email 'nikhilbrai@gmail.com'
          git status
          git add .
          git commit -m "Add coverage report for commit $LATEST_MASTER_COMMIT"
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

      - name: Set Coverage URL
        run: |
          echo "COVERAGE_URL=https://nikhilbrai.github.io/sonar-bazel-coverage/$LATEST_MASTER_COMMIT" >> $GITHUB_ENV
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            https://nikhilbrai.github.io/sonar-bazel-coverage/$LATEST_MASTER_COMMIT

  deploy:
    needs: build-and-coverage
    environment:
      name: github-pages
      url: ${{ env.COVERAGE_URL }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Upload artifact to dynamically generated folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: "java/spring-boot/genhtml${{ needs.build-and-coverage.outputs.latest-commit-message }}"  # Upload to a directory named by the commit SHA

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4